
secrets:
  db_password.txt:
    file: ../secrets/db_password.txt
  db_root_password.txt:
    file: ../secrets/db_root_password.txt
services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb:1.0
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_volume:/var/lib/mysql
    restart: always
    networks:
      - inception_network
    secrets:
      - db_password.txt
      - db_root_password.txt

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:1.0
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
    networks:
      - inception_network
    secrets:
      - db_password.txt

  nginx:
    build: ./requirements/nginx
    image: nginx:1.0
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
    networks:
      - inception_network

volumes:
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nfakih/data/mysql
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nfakih/data/wordpress

networks:
  inception_network:
    driver: bridge