version: '3.8'

services:
  mariadb:
    build: ./mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - db_volume:/var/lib/mysql
    restart: always
    networks:
      - inception_network

  wordpress:
    build: ./wordpress
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
    networks:
      - inception_network

  nginx:
    build: ./nginx
    container_name: nginx
    env_file: .env
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress_volume:/var/www/html
    restart: always
    networks:
      - inception_network

volumes:
  db_volume:
  wordpress_volume:

networks:
  inception_network:
    driver: bridge