events {
    worker_connections 1024;
}
#each nginx worker process can handle up to 1024 connections
#required by nginx

http {
    server {
        listen 443 ssl;
        server_name nfakih.42.fr;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        ssl_protocols TLSv1.3;
        root /var/www/html;
        index index.html;
        
        location / {
            try_files $uri $uri/ =404;
        }
    }
}
#without try files everything would be sent to wordpress, here we're processing 
#existent files or directories first, else wordpress

#fir anything ending in php, talk to php-fpm on port 9000
#setting index.html as default
# params are just the common settinsg that come with php