[www]

user = www-data

group = www-data #security
listen = 0.0.0.0:9000 #accept on port 9000 

pm = dynamic

pm.start_servers = 2
pm.min_spare_servers = 1

pm.max_spare_servers = 3
pm.max_children = 5
# all for worker processes
clear_env = no
# so we can take from our own env